fix cross buildtools
actboy168/lua-debug pull request #175
Opened 2022-05-18 02:40 UTC by fesily

2022-05-18 13:18 UTC, actboy168 requested changes

2022-05-18 13:18 UTC, actboy168 commented on compile/common/runtime.lua
> +			if lm.target_arch ~= lm.arch then
应该在detect_platform.lua里判断是否需要交叉编译，减少detect_platform.lua和其他文件的耦合。

2022-05-18 13:18 UTC, actboy168 commented on compile/luajit/defined.lua
> +local arch = require "compile.common.detect_platform".detect_target_arch(lm.runtime_platform or lm.platform)
只是一个简单的字符串分割，没必要引用detect_platform.lua

2022-05-19 05:55 UTC, fesily commented on compile/common/runtime.lua
> +			if lm.target_arch ~= lm.arch then
现在编译有三个入口,正常make读取所有文件,mac arm64 交叉编译x64时直接调了runtime.lua, luajit buildtools还有一个编译入口.原来的代码就第一个入口引用了detect_platform.之后二个交叉编译的时候还是需要detect_platform信息的吧.你想减少耦合,那么这个相关判断需要copy 好几份扔到不同的文件里去

2022-05-19 05:56 UTC, fesily commented on compile/common/runtime.lua
> +			if lm.target_arch ~= lm.arch then
倒是可以把target_arch的处理放到detect_platform里面 然后各自引用一次detect_platform文件

2022-05-19 07:23 UTC, actboy168 requested changes

2022-05-19 07:23 UTC, actboy168 commented on compile/common/detect_platform.lua
>                  lm.cc = "aarch64-linux-gnu-gcc"
这里可以直接设置`lm.cross_compile=true`，不需要其他复杂的判断逻辑。对于macos，arm64的平台可以运行x86_64的可执行文件，所以只需要保证在x86_64平台编译arm64版本时激活交叉编译即可。

2022-05-19 07:23 UTC, actboy168 commented on compile/luajit/make_buildtools.lua
> +if lm.cross_arch then
这个看起来没有用

2022-05-20 05:09 UTC, actboy168 requested changes

2022-05-20 05:09 UTC, actboy168 commented on compile/luajit/make_buildtools.lua
> +    lm:default {
这里应该不需要指定default

2022-05-23 01:37 UTC, merged