Cfuntion show more
actboy168/lua-debug pull request #214
Opened 2023-01-13 09:06 UTC by fesily

<img width="724" alt="image" src="https://user-images.githubusercontent.com/15152525/212281007-54b6bf70-af45-49bb-a495-18c6f93e08a1.png">

2023-01-13 09:26 UTC, actboy168 commented
想法不错。不过使用popen不是一个好主意，这会有很多安全性的问题。

2023-01-14 03:50 UTC, fesily commented
我不太明白，作为调试器本身就拥有极高权限，代码又是动态加载的，跟安全性应该搭不上边吧

2023-01-16 01:57 UTC, actboy168 commented
> 我不太明白，作为调试器本身就拥有极高权限，代码又是动态加载的，跟安全性应该搭不上边吧

但还是尽量不和外部程序形成依赖。

windows部分的实现思路，我觉得就很好。不过我可能在过年前没有时间做完整的review。

2023-01-16 02:03 UTC, actboy168 requested changes

2023-01-16 02:03 UTC, actboy168 commented on src/remotedebug/rdebug_visitor.cpp
> +	static NativeInfo::LuaCFunctionInfo infos;
缓存，我认为是没必要的。即使要做也应该在lua里做。

2023-01-16 02:35 UTC, fesily commented
> > 我不太明白，作为调试器本身就拥有极高权限，代码又是动态加载的，跟安全性应该搭不上边吧
> 
> 但还是尽量不和外部程序形成依赖。
> 
> windows部分的实现思路，我觉得就很好。不过我可能在过年前没有时间做完整的review。

不依赖外部程序,那就只能依赖外部库了,比如libdwarf,工程量不小

2023-01-16 02:41 UTC, fesily commented on src/remotedebug/rdebug_visitor.cpp
> +	static NativeInfo::LuaCFunctionInfo infos;
这个操作很慢的.绑定不同upvalue的cfunction在lua中对象是不同的.

2023-01-16 02:59 UTC, fesily commented on src/remotedebug/rdebug_visitor.cpp
> +	static NativeInfo::LuaCFunctionInfo infos;
不过目前是延迟加载的,不缓存也没事

2023-01-19 08:11 UTC, fesily commented
不知道哪里被破坏了,master的代码会报
```log
[2023-01-19 16:07:36:010][....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua: 55][ERROR]ERROR:...bug-1.61.0-darwin-arm64/script/backend/worker/luaver.lua:7: bad argument #1 to 'fieldv' (table expected, got userdata)
stack traceback:
	[C]: in function 'remotedebug.visitor.fieldv'
	...bug-1.61.0-darwin-arm64/script/backend/worker/luaver.lua:7: in function 'backend.worker.luaver.init'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:113: in local 'f'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:51: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:48>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:48: in upvalue 'workerThreadUpdate'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:603: in upvalue 'debuggeeReady'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:816: in field '?'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:830: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:827>
[2023-01-19 16:07:36:011][....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua: 55][ERROR]ERROR:....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:546: bad argument #1 to 'field' (table expected, got userdata)
stack traceback:
	[C]: in function 'remotedebug.visitor.field'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:546: in local 'set_search_path'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:551: in local 'f'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:51: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:48>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:48: in upvalue 'workerThreadUpdate'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:603: in upvalue 'debuggeeReady'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:816: in field '?'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:830: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:827>
[2023-01-19 16:07:36:011][....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:834][ERROR]ERROR:...debug-1.61.0-darwin-arm64/script/backend/worker/eval.lua:46: attempt to compare nil with number
stack traceback:
	...debug-1.61.0-darwin-arm64/script/backend/worker/eval.lua:46: in upvalue 'init'
	...debug-1.61.0-darwin-arm64/script/backend/worker/eval.lua:39: in function 'backend.worker.eval.dump'
	...bug-1.61.0-darwin-arm64/script/backend/worker/parser.lua:7: in upvalue 'getproto'
	...bug-1.61.0-darwin-arm64/script/backend/worker/parser.lua:98: in function 'backend.worker.parser'
	...1.61.0-darwin-arm64/script/backend/worker/breakpoint.lua:198: in upvalue 'calcLineInfo'
	...1.61.0-darwin-arm64/script/backend/worker/breakpoint.lua:280: in function 'backend.worker.breakpoint.newproto'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:661: in field '?'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:830: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:827>
[2023-01-19 16:07:36:016][....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua: 55][ERROR]ERROR:....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:149: attempt to compare number with nil
stack traceback:
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:149: in upvalue 'getFuncName'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:192: in upvalue 'stackTrace'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:268: in local 'f'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:51: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:48>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:48: in upvalue 'workerThreadUpdate'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:576: in upvalue 'runLoop'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:648: in field '?'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:830: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828>
	[C]: in function 'xpcall'
	....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:828: in function <....lua-debug-1.61.0-darwin-arm64/script/backend/worker.lua:827>

```

2023-02-08 08:02 UTC, actboy168 commented
windows下已经没什么问题了。不过我在macos上测试，速度很慢。

2023-02-08 08:10 UTC, fesily commented
> windows下已经没什么问题了。不过我在macos上测试，速度很慢。

我用M1,基本没感知. 你的机器大概要多久读一次

2023-02-08 08:25 UTC, actboy168 commented
我的也是m1，打开Standard，大概需要10秒。

2023-02-08 09:02 UTC, fesily commented
> 我的也是m1，打开Standard，大概需要10秒。

单次请求的确得差不多1S请求十个就得10S了,在linux上一样会很慢的.
两个方向
1. 可以批量读取,这两程序都支持这个
2. 标记这种类型的变量lazy

2023-02-10 06:05 UTC, fesily commented
在合并dobby库之后直接使用dobby内置的解析符号功能,就不用调用外部程序了

2023-02-10 06:50 UTC, actboy168 commented
> 在合并dobby库之后直接使用dobby内置的解析符号功能,就不用调用外部程序了

我先合并了，你之后再改吧。

2023-02-10 06:51 UTC, merged