support linux/macos inject
actboy168/lua-debug pull request #216
Opened 2023-02-02 01:59 UTC by fesily

- [x] macos inject
- [ ] linux inject

2023-02-02 03:05 UTC, actboy168 commented
看起来不错。

我看Dobby的描述是一个跨平台的hook库，是否可以在windows上替代detours？如果可以，我认为可以把detours去掉。

我不想依赖cmake，所以还得给Dobby写个luamake的构建脚本。(这个可以我来做)

2023-02-02 03:22 UTC, fesily commented
可以替代detours.  我写的代码是通用的, 直接删掉autoattach.cpp中_WIN32的部分就完事

现在主要有两个问题
1.如果要支持远程注入ios和android的话,这个库实现不了,还是得和gdb/lldb的server进程通信才有可以.
2.现在劫持的三个函数有问题,纯lua环境不调这三个接口的话永远不会执行attach函数

所以我有进一步的想法,hook的时候得多加一步.
1. 暂停进程
2. 遍历进程的所有线程
3. 查看线程有没有在执行Lua库的函数
4. 有的话,attach函数直接在该线程的环境中执行,不需要在继续hook函数了

2023-02-02 03:31 UTC, fesily commented
```c++
void initialize(fn_attach attach, bool ap) {
		if (debuggerAttach) {
			if (!attachProcess && ap && hookDll) {
				attachProcess = ap;
				lua::hook(hookDll);
			}
			return;
		}
		debuggerAttach = attach;
		attachProcess  = ap;
		if (!findLuaDll()) {
			waitLuaDll();
		}
	}
```
我不太明白第一个分支是什么样的情况才会出现

2023-02-02 03:36 UTC, actboy168 commented
> 可以替代detours. 我写的代码是通用的, 直接删掉autoattach.cpp中_WIN32的部分就完事
> 
> 现在主要有两个问题 1.如果要支持远程注入ios和android的话,这个库实现不了,还是得和gdb/lldb的server进程通信才有可以. 2.现在劫持的三个函数有问题,纯lua环境不调这三个接口的话永远不会执行attach函数
> 
> 所以我有进一步的想法,hook的时候得多加一步.
> 
> 1. 暂停进程
> 2. 遍历进程的所有线程
> 3. 查看线程有没有在执行Lua库的函数
> 4. 有的话,attach函数直接在该线程的环境中执行,不需要在继续hook函数了

一个线程可能有三种可能
1. 正在执行某个lua函数。可以attach，但你必须等待这个lua函数返回时才能attach。还是得hook。
2. 没有在执行某个lua函数，但可能未来会执行lua函数。这种情形似乎没有办法可以attach。
3. 跟lua无关的线程。

2023-02-02 03:45 UTC, actboy168 commented
> ```c++
> void initialize(fn_attach attach, bool ap) {
> 		if (debuggerAttach) {
> 			if (!attachProcess && ap && hookDll) {
> 				attachProcess = ap;
> 				lua::hook(hookDll);
> 			}
> 			return;
> 		}
> 		debuggerAttach = attach;
> 		attachProcess  = ap;
> 		if (!findLuaDll()) {
> 			waitLuaDll();
> 		}
> 	}
> ```
> 
> 我不太明白第一个分支是什么样的情况才会出现

很久以前的代码了，可能没用了

2023-02-02 04:17 UTC, fesily commented
> > 可以替代detours. 我写的代码是通用的, 直接删掉autoattach.cpp中_WIN32的部分就完事
> > 现在主要有两个问题 1.如果要支持远程注入ios和android的话,这个库实现不了,还是得和gdb/lldb的server进程通信才有可以. 2.现在劫持的三个函数有问题,纯lua环境不调这三个接口的话永远不会执行attach函数
> > 所以我有进一步的想法,hook的时候得多加一步.
> > 
> > 1. 暂停进程
> > 2. 遍历进程的所有线程
> > 3. 查看线程有没有在执行Lua库的函数
> > 4. 有的话,attach函数直接在该线程的环境中执行,不需要在继续hook函数了
> 
> 一个线程可能有三种可能
> 
> 1. 正在执行某个lua函数。可以attach，但你必须等待这个lua函数返回时才能attach。还是得hook。
> 2. 没有在执行某个lua函数，但可能未来会执行lua函数。这种情形似乎没有办法可以attach。
> 3. 跟lua无关的线程。

我说的就是第一种情况,其实不需要等待他函数返回,直接记录存下当前所有的寄存器信息,然后PC指向shellcode,运行完还原就行了,调试器都是这样干的

2023-02-02 04:30 UTC, actboy168 commented
attach现在会跑很多lua代码，只是保护寄存器信息还不够。当然attach理论上只有调用lua_sethook是必须，其它事情都不是必须的或者是可以移到其他时机做。

2023-02-02 04:40 UTC, actboy168 commented
你的这套方案就算做完也不能完全替代hook的方案，只能作为一个补充。

所以我的观点是可以做，但没必要。自动inject的方式，在lua vm不主动帮忙的情况下，终究很难做得很好。而且和手动inject比，优点可能只是对新手友好一点，缺点一大堆。而对于新手来说直接launch lua，就够了，对于重度使用的工程，手动inject是最佳选择，代价也只是多写几行代码。

2023-02-02 05:53 UTC, fesily commented
> 你的这套方案就算做完也不能完全替代hook的方案，只能作为一个补充。
> 
> 所以我的观点是可以做，但没必要。自动inject的方式，在lua vm不主动帮忙的情况下，终究很难做得很好。而且和手动inject比，优点可能只是对新手友好一点，缺点一大堆。而对于新手来说直接launch lua，就够了，对于重度使用的工程，手动inject是最佳选择，代价也只是多写几行代码。

这个出发点不一样,你这个前提是能修改代码,如果不能改代码呢.

2023-02-02 06:52 UTC, fesily commented
说个直观点的例子,好多游戏给的MOD开发接中的lua代码是纯沙盒,压根不支持去加载动态库.对外的所有IO端口也是关闭的,这个除了注入估计没啥办法了.

2023-02-02 07:25 UTC, actboy168 commented
想法是挺好的。就算是c++的调试器也调试不了没有调试符号的程序，调试本来就算调试目标和调试器相互配合的过程。当然你可以说你的目标是和windbg这样的汇编级的调试器一样，可以调试任何进程。但是在更好用的调试还适用的情况下，没人会选择windbg，不是吗？

不过我不反对你做这方面的探索。

2023-02-02 08:30 UTC, fesily commented
> 想法是挺好的。就算是c++的调试器也调试不了没有调试符号的程序，调试本来就算调试目标和调试器相互配合的过程。当然你可以说你的目标是和windbg这样的汇编级的调试器一样，可以调试任何进程。但是在更好用的调试还适用的情况下，没人会选择windbg，不是吗？
> 
> 不过我不反对你做这方面的探索。

如果能相互配合的话,根本就不需要提供这么复杂的工具.

没调试符号的问题也可以解决的.提供特征码入口就行,让mod作者自己搞定特征码.

2023-02-08 06:06 UTC, actboy168 commented
这里也有injectdll，应该也需要做对应的修改
https://github.com/actboy168/lua-debug/blob/master/extension/script/frontend/debuger_factory.lua#L224

2023-02-08 08:58 UTC, actboy168 commented
似乎没有任何地方用到ShellcodeCompiler？

2023-02-08 09:10 UTC, fesily commented
> 似乎没有任何地方用到ShellcodeCompiler？

我没写这么用,就是inject_macos.cpp中的inject_code由这个程序生成, python3 tools/ShellcodeCompiler/ShellcodeCompiler.py src/process_inject/macos/shellcode.cc

2023-02-09 08:28 UTC, fesily commented on compile/macos/export_shellcode.lua
> +    elseif line:sub(1, 6):match "^ [0-9a-f][0-9a-f][0-9a-f][0-9a-f] $" then
不单单是8个
有可能是
00
5f00 
5faa00

2023-02-09 08:32 UTC, actboy168 commented on compile/macos/export_shellcode.lua
> +    elseif line:sub(1, 6):match "^ [0-9a-f][0-9a-f][0-9a-f][0-9a-f] $" then
哪里有8？

2023-02-09 08:35 UTC, fesily commented on compile/macos/export_shellcode.lua
> +    elseif line:sub(1, 6):match "^ [0-9a-f][0-9a-f][0-9a-f][0-9a-f] $" then
3fb0 656c665f 00
3fb0 656c665f 5faa00
之前的逻辑有点小问题, 不能处理这两种情况的

2023-02-09 08:35 UTC, fesily commented on compile/macos/export_shellcode.lua
> +    elseif line:sub(1, 6):match "^ [0-9a-f][0-9a-f][0-9a-f][0-9a-f] $" then
现在的shellcode生成的就是第一种情况

2023-02-09 09:10 UTC, fesily commented on compile/macos/export_shellcode.lua
> +    elseif line:sub(1, 6):match "^ [0-9a-f][0-9a-f][0-9a-f][0-9a-f] $" then
嗯,这个没问题,我测试了一下,逻辑写错了,这个功能是依赖于text和cstring段必须要生成在一起才可以有效的

2023-02-09 09:12 UTC, actboy168 commented on compile/macos/export_shellcode.lua
> +    elseif line:sub(1, 6):match "^ [0-9a-f][0-9a-f][0-9a-f][0-9a-f] $" then
我写的时候就想过这个问题，不过还是保持和你原来的逻辑一致。

2023-02-09 09:57 UTC, actboy168 commented
目前我还不能在macos上正确运行，我先把它改为Draft。等你做完，你再改回来。

另外，这个pull request已经非常巨大，我建议是把macos inject和你重写attach的代码切割为两个pull request。

2023-02-10 07:16 UTC, fesily commented
当前版本已经可以在m1上注入并启动了, 但是有点奇怪的是进程初始化的时候才十几个动态库,注入加载完debugger后150多个动态库.

2023-02-17 08:21 UTC, actboy168 commented
windows还编译不了

2023-02-17 12:57 UTC, actboy168 requested changes

2023-02-17 12:57 UTC, actboy168 commented on src/launcher/main.cpp
> +	lua_pushlstring(L, (const char*)(void**)&autoattach::luaapi, sizeof(void*));
为什么要改成string?

2023-02-17 13:06 UTC, actboy168 commented
新的注入方式，似乎没有在windows上生效？

2023-02-17 13:29 UTC, fesily commented on src/launcher/main.cpp
> +	lua_pushlstring(L, (const char*)(void**)&autoattach::luaapi, sizeof(void*));
因为我想要尽量减少依赖的api，只使用必要的。尤其在无符号的情况下，每减少一个，成功率会更高一点，兼容性也更好。

2023-02-17 13:35 UTC, fesily commented
> 新的注入方式，似乎没有在windows上生效？

对，明天改

2023-02-17 13:45 UTC, actboy168 commented on src/launcher/main.cpp
> +	lua_pushlstring(L, (const char*)(void**)&autoattach::luaapi, sizeof(void*));
如此lua_pushstring应该也可以用lua_pushlstring代替。

2023-02-20 07:10 UTC, fesily commented
这个延迟绑定的lua54是为了在lua模块未加载前,launcher加载了,而准备的吧?

2023-02-20 07:41 UTC, actboy168 commented
> 这个延迟绑定的lua54是为了在lua模块未加载前,launcher加载了,而准备的吧?

即使是launch加载时，已经存在lua模块，但由于不可能提前得知lua模块的名字，所以依然无法把相同名字的lua模块link到launch里。延迟加载就可以在不提前假定lua模块名的情况下，用正常的方式使用lua的函数。

2023-02-20 08:31 UTC, fesily commented
了解了,那等于说直接去遍历所有模块来解析符号的话,这个延迟绑定已经是没有用的了.不存在这个问题了.因为launcher本身已经不是隐式导入而是明确的导入

2023-02-20 08:35 UTC, actboy168 commented
我在windows上跑不了。简单debug一下，就触发了一个断言。

这里计算内存地址，从头到尾都只是模了`PageSize()`
https://github.com/fesily/Dobby/blob/master/source/MemoryAllocator/NearMemoryAllocator.cc#L161
但在检查时却要求内存地址模`AllocPageSize()`为0
https://github.com/fesily/Dobby/blob/master/source/Backend/UserMode/UnifiedInterface/platform-windows.cc#L39

所以这两个地方必然有一个错了。

2023-02-20 08:55 UTC, actboy168 commented
> 了解了,那等于说直接去遍历所有模块来解析符号的话,这个延迟绑定已经是没有用的了.不存在这个问题了.因为launcher本身已经不是隐式导入而是明确的导入

是的。不过由于remotedebug还是使用老的方法查找符号，所以最终没有区别。

另外，我建议是把attach_args改个名字，然后为所有lua函数/类型改个名字，不和lua.h里的名字重复。这样会看起来更清晰，也方便今后remotedebug复用代码。

例如 
``` c++
namespace lua {
        using state = intptr_t;
        void  (*pushlstring)(state L, const char *s, size_t l);
}
```

2023-02-20 09:18 UTC, fesily commented
时机上remotedebug加载的时候肯定已经有符号了.launcher不一定有.

2023-02-20 09:26 UTC, actboy168 commented
remotedebug不能解决的问题是lua被静态编译进了调试目标，没有把导出函数。

2023-02-21 00:56 UTC, fesily commented
嗯,的确有这个问题,可以主动加载remotedebug并修复导入表,解决这个问题

2023-02-21 06:03 UTC, actboy168 requested changes

2023-02-21 06:03 UTC, actboy168 commented on src/launcher/attach_args.cpp
> +        SymbolResolverWithCheck(settop);
这个看起来应该是SymbolResolverWithCheck_lua。

此外，现在的SymbolResolver有个问题。GetProcAddress是很快的，但是SymbolResolver的其他代码比较慢。大多数的情况下GetProcAddress就能解决问题，但是像pcallk/pcall这样的总是需要找两次，所以总是至少会经历一次较慢的查找。所以对于pcallk/pcall只需要找到其中一个的情况下，应该先用GetProcAddress，都找不到才开始比较慢的查找。

2023-02-21 06:15 UTC, actboy168 commented
从这函数看出，它只支持kReadWriteExecute和kReadExecute。但只需要搜索代码就知道它还有其他值，比如kWriteExecute。
https://github.com/fesily/Dobby/blob/master/source/Backend/UserMode/UnifiedInterface/platform-windows.cc#L10-L16

不明白为何dobby有这么多低级错误，看起来这个库质量一般。

2023-02-21 06:25 UTC, fesily commented
> 从这函数看出，它只支持kReadWriteExecute和kReadExecute。但只需要搜索代码就知道它还有其他值，比如kReadWrite。 https://github.com/fesily/Dobby/blob/master/source/Backend/UserMode/UnifiedInterface/platform-windows.cc#L10-L16
> 
> 不明白为何dobby有这么多低级错误，看起来这个库质量一般。

嗯,我之前没注意他的windows部分,基本上等于残废.他其实就没好好实现windows部分

2023-02-21 07:46 UTC, fesily commented
x64注入的代码好像有点问题,根本起不来,直接访问异常了

![image](https://user-images.githubusercontent.com/15152525/220280300-dcfb5730-60a7-4be8-a6d7-cfd599c1f8a5.png)
MSVC143, Windows server 2019,我尝试了市场里当前的版本(release)和我这边的最新版(debug)

2023-02-21 08:07 UTC, actboy168 commented
> x64注入的代码好像有点问题,根本起不来,直接访问异常了
> 
> ![image](https://user-images.githubusercontent.com/15152525/220280300-dcfb5730-60a7-4be8-a6d7-cfd599c1f8a5.png) MSVC143, Windows server 2019,我尝试了市场里当前的版本(release)和我这边的最新版(debug)

没用过server版，你调试下看看？

2023-02-21 08:11 UTC, fesily commented
> 

x86是正常的

2023-02-21 08:15 UTC, actboy168 commented
可能wow64ext有问题。可以绕过的话，就先不管吧。我其实是想去掉它，然后改成运行一个64位的辅助进程来注入64位进程这样的。

2023-02-21 10:16 UTC, actboy168 commented
嗯，我在windows依然会挂在dobby里。或许我们可以在windows下的hook依然使用detours。

但由于我在macos下也运行不了，所以不知道dobby是不是在全平台都是有问题。

2023-02-21 12:31 UTC, fesily commented
> 嗯，我在windows依然会挂在dobby里。或许我们可以在windows下的hook依然使用detours。
> 
> 但由于我在macos下也运行不了，所以不知道dobby是不是在全平台都是有问题。

windows下我也运行不了,dobby返回的代码生成的不太对. macos你那边是什么问题?

2023-02-21 15:02 UTC, actboy168 commented
基于我昨天说的思路，我重写了attach_args。主要目的是为了方便之后和remotedebug复用代码。不过还有一些工作未完成。

* 我对luajit不是很熟悉，所以没有修改luajit的代码，留给你来改。我把launch里引用的lua.h从luajit改为lua54.因为lua54是所有lua版本的符号的超集，remotedebug里会用到很多lua54/lua53的符号，这些是luajit没有的。而luajit专有的符号应该都不在lua.h里，所以应该不会有冲突。
* lua_resovler之后也会被remotedebug复用。autoattach.cpp里也包含了很多初始化resovler的代码，它们应该也需要剥离出来。

2023-02-22 03:44 UTC, fesily commented
我仔细测试了了x86下的dobby,x86和x64都是错的,没一个正确的.我看了他的commit的基本都集中在iPhone和android平台
我决定使用frida-gum替换掉Dobby

2023-02-22 03:59 UTC, fesily commented
不过我得在挣扎一下,确定不是我后面添加的代码导致的Dobby运行错误

2023-02-22 06:22 UTC, actboy168 commented
我整理了launch需要完成的工作，分为三步

1. 搜索需要hook的地址。
2. hook。
3. 加载attach.lua。

对于3，这个PR应该已经做得很好了。只是搜索符号的代码看似是引用了dobby，但我看实际上是你fork dobby后改的。所以不是很有必要还把代码放dobby里。
对于2，detours在windows下工作得很好，dobby或者其他的hook还需验证。所以我觉得暂时可以在windows下用detours，macos用dobby或者其他hook库。
对于1，现有的方法虽然不完美，但至少还能工作。你新写的还有待验证。

所以现在的PR虽然已经拆分过一次，但依然有点大，一次想解决的问题太多。我觉得可以先做一个macos可以正常工作的版本，再做其他改进方案。也就是对于以上三步

1. 用现在windows版本的思路做一个macos版本。
2. windows用detours，macos用dobby。
3. 保留现在PR里的实现。

2023-02-23 10:06 UTC, fesily commented
我已经改的差不多了。现在添加了hook测试代码。但是还是不能运行起来，还差一步符号解析

2023-02-23 11:51 UTC, actboy168 commented
frida-gum.lib是什么，为什么不是从源码构建的？

2023-02-23 12:31 UTC, fesily commented
源码构建还需要glib

2023-02-23 13:02 UTC, actboy168 commented
不能源码构建的话，维护起来会很麻烦。所以还是换一个库吧。detours在windows下就挺好的。

2023-02-24 01:08 UTC, fesily commented
> 不能源码构建的话，维护起来会很麻烦。所以还是换一个库吧。detours在windows下就挺好的。

[frida](https://github.com/frida/frida/releases/tag/16.0.10)本来就提供全平台的sdk,你可以看看这个库的概要,比dobby的应用范围要广.
Dobby也是抄的frida,提取了一部分的功能.

可以源码构建,但是现阶段我觉得没有必要.我想先实现功能,源码构建什么的,可以在完成功能了在加进去.

detours在windows上的确独树一帜,问题是他只提供了hook的方式,没有动态打桩的方法,咱们现在不是统一成动态打桩的形式了嘛

2023-02-24 02:42 UTC, actboy168 commented
我觉得现在优先需要考虑的问题是，如何让这个庞大的PR顺利合并。对于一个已经大量代码的仓库来说，这不是一个容易的事情。

现在这个分支上提交了四个静态库，直接就让这个仓库的大小翻了几倍，在不翻墙的情况下，clone都成问题。launcher并不是调试器的核心，大多数编译调试器的人并不需要launcher。

我不抗拒最终调试器会引入frida或者别的什么库，但现在应该先考虑如何让launcher能正确工作，动态打桩可以下一步再做。上一个PR的macos进程注入的代码，也等着launcher来验证。

2023-02-24 04:24 UTC, fesily commented on src/launcher/lua_delayload.h
> +        STRING_FIND("__");
不能处理这种情况 auto __cdecl lua_delayload::impl::symbol<void (__cdecl *__cdecl lua_gethook(struct lua_State *))(struct lua_State *,struct lua_Debug *)>(void) noexcept

2023-02-24 04:59 UTC, fesily commented
> 我觉得现在优先需要考虑的问题是，如何让这个庞大的PR顺利合并。对于一个已经大量代码的仓库来说，这不是一个容易的事情。
> 
> 现在这个分支上提交了四个静态库，直接就让这个仓库的大小翻了几倍，在不翻墙的情况下，clone都成问题。launcher并不是调试器的核心，大多数编译调试器的人并不需要launcher。

既然担心大小的问题,我改成只下载必要的依赖库

2023-02-24 06:33 UTC, actboy168 commented on src/launcher/lua_delayload.h
> +        STRING_FIND("__");
最后一次改成find "lua"？毕竟所有的函数都是lua开头的

2023-02-24 06:40 UTC, actboy168 commented
> 既然担心大小的问题,我改成只下载必要的依赖库

我只是随便举个例子。我想说的是完成这个PR有很多事情要做，整合frida库，符号搜索，新的hook方式，macos进程注入等等等等。我希望对这些工作排一个优先级，尽快完全一部分验证。而不是把所有工作都做完，一起验证。

2023-02-24 06:48 UTC, fesily commented on src/launcher/lua_delayload.h
> +        STRING_FIND("__");
我先在windows上改一个版本,加了一个对应的测试

2023-02-24 06:57 UTC, fesily commented
> > 既然担心大小的问题,我改成只下载必要的依赖库
> 
> 我只是随便举个例子。我想说的是完成这个PR有很多事情要做，整合frida库，符号搜索，新的hook方式，macos进程注入等等等等。我希望对这些工作排一个优先级，尽快完全一部分验证。而不是把所有工作都做完，一起验证。

先解决macos进程注入这个问题吧 在你电脑上现在是什么情况,测试用例是通过的对吧?

2023-02-24 07:48 UTC, actboy168 commented
现在这个PR在macos编译不了，所以我还没有试。

2023-02-24 08:17 UTC, fesily commented
> 现在这个PR在macos编译不了，所以我还没有试。

master分支的.macos注入的功能不是已经合并了

2023-02-24 08:19 UTC, actboy168 commented
master上的launcher是不对的，之前有想过我自己写一个最简单的launcher来测试。但考虑到这个PR在解决launcher的问题，就还没有做。

2023-02-24 08:24 UTC, fesily commented
> master上的launcher是不对的，之前有想过我自己写一个最简单的launcher来测试。但考虑到这个PR在解决launcher的问题，就还没有做。

我记得master的inject的测试应该是成功的吧,不过是launcher部分没写而已

2023-02-24 08:26 UTC, fesily commented
现在windows上初步可以了, 我已经attach到自带的lua进程了

2023-02-24 08:39 UTC, actboy168 commented
这个PR也改了process_inject，如果有必要改，应该另开一个PR，先合并到master。

2023-02-24 08:40 UTC, fesily commented
> 这个PR也改了process_inject，如果有必要改，应该另开一个PR，先合并到master。

👌

2023-02-24 09:41 UTC, actboy168 commented
> 先解决macos进程注入这个问题吧 在你电脑上现在是什么情况,测试用例是通过的对吧?

刚试了下，inject=hook就是task_for_pid失败，inject=lldb就无响应

2023-02-24 09:49 UTC, fesily commented
测试用例能过吗？这样也不知道是注入失败了，还是launcher出错了

2023-02-24 09:52 UTC, actboy168 commented
测试是能过的。task_for_pid失败还没到launcher加载吧

2023-02-24 09:58 UTC, actboy168 commented
这个RP，我在windows上还编译不了。我觉得这个RP如果不切割，离能合并还很遥远。

2023-02-24 10:30 UTC, fesily commented
嗯，需要分割一下，你现在编译什么错误？

2023-02-24 10:51 UTC, actboy168 commented
frida的头文件找不到

2023-02-24 10:53 UTC, fesily commented
> frida的头文件找不到

之前自动下载的，但是不知道为什么ci总是提示失败，依赖有点问题
luamke lua compiler/update_frida_gum.lua

2023-02-24 11:37 UTC, actboy168 commented
这个脚本我已经运行过了，但可能没完整下载？

2023-02-24 11:43 UTC, fesily commented
> 这个脚本我已经运行过了，但可能没完整下载？

我换台电脑试了一下,`3rd\frida_gum`路径下有`3rd\frida_gum\windows-x86`和`3rd\frida_gum\windows-x86_64`,没有吗

2023-02-24 15:37 UTC, actboy168 commented
你可以参考下我最初说的拆分思路。
1.搜索hook地址，沿用目前思路，实现macos版本。
2.hook库，windows用detours，macos用其他库。
3.重点是合并搜索lua的函数相关的代码。

也就是先完成3，12尽量保持不变。然后再依次完成2和1。

2023-02-24 15:40 UTC, actboy168 commented
对于3，无论是用dobby还是frida，我看你基本都是大幅度修改它们的代码，所以似乎没有再使用这些库的必要，你直接写一个好了。

2023-02-25 02:47 UTC, fesily commented
> 对于3，无论是用dobby还是frida，我看你基本都是大幅度修改它们的代码，所以似乎没有再使用这些库的必要，你直接写一个好了。

都只是修改了Windows上的解析,frida其实是正确的,只不过没加载正确的符号

2023-02-25 12:28 UTC, actboy168 commented
看了下下载frida的脚本，下载exe下来再我的机器上是无法执行的，可能是安全策略的原因？但是我看了下windows也有tar.xz，改成下载tar.xz就可以了。

另一个问题是，如果检测有已经下载好的文件，就跳过了。但是有可能我已经下载好了文件，但是解压失败了。只能手动删掉下载文件，再次执行脚本。

2023-02-25 12:39 UTC, actboy168 commented
> > 对于3，无论是用dobby还是frida，我看你基本都是大幅度修改它们的代码，所以似乎没有再使用这些库的必要，你直接写一个好了。
> 
> 都只是修改了Windows上的解析,frida其实是正确的,只不过没加载正确的符号

给frida提PR？如果只是了修改windows的版本，不如windows的就直接自己写。

2023-02-25 13:08 UTC, fesily commented
> 给frida提PR？如果只是了修改windows的版本，不如windows的就直接自己写。

嗯，自己写，我已经找到办法了，直接写同样签名的函数覆盖他的就好了

2023-02-25 13:13 UTC, fesily commented
> 看了下下载frida的脚本，下载exe下来在我的机器上是无法执行的，可能是安全策略的原因？但是我看了下windows也有tar.xz，改成下载tar.xz就可以了。
> 
> 另一个问题是，如果检测有已经下载好的文件，就跳过了。但是有可能我已经下载好了文件，而解压失败了。只能手动删掉下载文件，再次执行脚本。

我电脑上无法自动解压，装了7z也解压不出来，

2023-02-25 13:19 UTC, fesily commented
> > 看了下下载frida的脚本，下载exe下来在我的机器上是无法执行的，可能是安全策略的原因？但是我看了下windows也有tar.xz，改成下载tar.xz就可以了。
> > 另一个问题是，如果检测有已经下载好的文件，就跳过了。但是有可能我已经下载好了文件，而解压失败了。只能手动删掉下载文件，再次执行脚本。
> 
> 我电脑上无法自动解压，装了7z也解压不出来，

可能是Windows server的系统导致的，tar检测功能有点问题

2023-02-25 13:41 UTC, actboy168 commented
> 
> > 给frida提PR？如果只是了修改windows的版本，不如windows的就直接自己写。
> 
> 嗯，自己写，我已经找到办法了，直接写同样签名的函数覆盖他的就好了
> 

不明白为什么要覆盖它的

2023-02-25 13:50 UTC, fesily commented
> > > 给frida提PR？如果只是了修改windows的版本，不如windows的就直接自己写。
> > 
> > 
> > 嗯，自己写，我已经找到办法了，直接写同样签名的函数覆盖他的就好了
> 
> 不明白为什么要覆盖它的

现在他不是只提供了库文件，几个错掉的函数可以使用同签名函数进行修复，也不用等他上游合并进去了。等他合并了，再删掉比较快

2023-02-26 13:33 UTC, fesily commented
> task_for_pid

task_for_pid失败的时候返回的错误信息是什么,一般来说root权限下这个api是错误的.当然这个可能取决于你的macos的版本

2023-02-27 01:22 UTC, actboy168 commented
> > task_for_pid
> 
> task_for_pid失败的时候返回的错误信息是什么,一般来说root权限下这个api是错误的.当然这个可能取决于你的macos的版本

0:268: execution error: task_for_pid (os/kern) failure (4)

2023-02-28 02:12 UTC, closed without merging