New launcher
actboy168/lua-debug pull request #222
Opened 2023-02-24 13:16 UTC by fesily

2023-02-27 01:35 UTC, fesily commented
什么时候方便的话,我们联调一下
我试了别人的三台m1都没有出现root权限下task_for_pid error,都是系统13,你是什么版本的系统.
有一种可能,你目前的系统需要签名,你可以试试自签名launcher和inject.

2023-02-27 03:07 UTC, actboy168 commented
操作系统是最新的。可能是我的杀毒软件搞的鬼。之前我就发觉它一些特别之处，比如xcode无法启动ios的app。

2023-02-27 04:47 UTC, fesily commented
那你确定一下,是不是杀毒软件搞的鬼,我这边的几台mac是都没有杀毒软件的

2023-02-27 04:54 UTC, actboy168 commented
有空我再研究下

2023-02-27 08:44 UTC, fesily commented
这种模式已经可以了
```json
		{
			"name": "attach",
			"request": "attach",
			"stopOnEntry": true,
			"type": "lua",
			"luaVersion": "jit",
			"processName": "lua"
		}
```

2023-02-27 09:15 UTC, fesily commented
```json
		{
			"name": "attach",
			"request": "attach",
			"stopOnEntry": true,
			"type": "lua",
			"luaVersion": "jit",
			"processName": "lua",
            "inject": "lldb",
		},
```
也是ok

2023-02-27 09:50 UTC, actboy168 commented
这个和#216的区别，只是windows下用了旧代码，macos用新代码？

2023-02-27 09:55 UTC, actboy168 requested changes

2023-02-27 09:55 UTC, actboy168 commented on src/launcher/lua_delayload.h
> +                return invoke != nullptr ? nullptr : symbol_name.data();
find任何情况下都不应该返回nullptr

2023-02-27 09:55 UTC, actboy168 commented on src/launcher/lua_resolver.cpp
> +        fprintf(stderr, "Fatal Error: Can't find lua c function: `%s`.", name);
这里应该改成log::fatal

2023-02-27 09:59 UTC, actboy168 commented
symbol_resolver目录下的几个文件感觉挺多余的，全部合并到lua_resolver.cpp里去好了

2023-02-27 10:03 UTC, fesily commented on src/launcher/lua_delayload.h
> +                return invoke != nullptr ? nullptr : symbol_name.data();
如果被裁剪掉的话，还是回返回null的，这个情况下不反错误继续往下就crash了

2023-02-27 10:31 UTC, actboy168 commented on src/launcher/lua_delayload.h
> +                return invoke != nullptr ? nullptr : symbol_name.data();
看下面find的实现，找不到就exit了

2023-02-27 11:27 UTC, fesily commented on src/launcher/lua_delayload.h
> +                return invoke != nullptr ? nullptr : symbol_name.data();
那不就是等同于crash了。这样等于扩散错误到宿主了。这属于错误不是异常吧，我同意异常应该立即终止，但是错误应该被处理掉

2023-02-27 11:28 UTC, fesily commented
> symbol_resolver目录下的几个文件感觉挺多余的，全部合并到lua_resolver.cpp里去好了

这里文件夹下我删了特征码扫描的部分，因为这块代码也挺大的，所以现在看起来抽象没什么用

2023-02-27 11:48 UTC, actboy168 commented on src/launcher/lua_delayload.h
> +                return invoke != nullptr ? nullptr : symbol_name.data();
确实可以处理得更好，但是现在find的实现的确是不会返回nullptr的。

2023-02-27 11:50 UTC, actboy168 commented
> > 这个和 #216 的区别，只是windows下用了旧代码，macos用新代码？
> 
> 基本上是这样，多了几个测试用例，核心代码就是这样，并且gumpp变成子模块了

如果是这样还不如把旧代码删了。我现在只能跑windows的版本，如果windows和这个pr无关，我就完全无法验证了。

2023-02-27 12:14 UTC, fesily commented on src/launcher/lua_delayload.h
> +                return invoke != nullptr ? nullptr : symbol_name.data();
嗯我改了,找不到就返回NULL就行

2023-02-27 12:14 UTC, fesily commented on src/launcher/lua_resolver.cpp
> +        fprintf(stderr, "Fatal Error: Can't find lua c function: `%s`.", name);
删掉了,直接返回NULl

2023-02-27 12:15 UTC, fesily commented
测试的时候暂时不要用launcher.inject的方式,我压根就没测试那种

2023-02-28 02:08 UTC, fesily commented
> > > 这个和 #216 的区别，只是windows下用了旧代码，macos用新代码？
> > 
> > 
> > 基本上是这样，多了几个测试用例，核心代码就是这样，并且gumpp变成子模块了
> 
> 如果是这样还不如把旧代码删了。我现在只能跑windows的版本，如果windows和这个pr无关，我就完全无法验证了。

我将关闭之前的pr, 将windows部分合并进来

2023-02-28 09:21 UTC, fesily commented
就剩最后一个我没通过了，macos中launcher模式好像压根新建不了进程。

2023-02-28 10:32 UTC, actboy168 commented
> 就剩最后一个我没通过了，macos中launcher模式好像压根新建不了进程。

我之前测的就是launch

2023-02-28 12:10 UTC, fesily commented
> > 就剩最后一个我没通过了，macos中launcher模式好像压根新建不了进程。
> 
> 我之前测的就是launch

我明天在看一下哪里出错了,我之前就没测过这个模式,现在attach都很🆗

2023-02-28 13:00 UTC, actboy168 commented
现在编译有很多警告

2023-02-28 13:15 UTC, actboy168 commented on src/launcher/symbol_resolver/gum_resolver.cpp
> +            auto key = keys.back().data();
这个spilt的作用是什么？

2023-02-28 13:33 UTC, fesily commented
> > > 现在编译有很多警告
> > 
> > 
> > 什么警告,windows下吗,frida-gum.h的编码错误吧.那个不用理会.其他我看了下也没有啊
> 
> ```
> 3rd/frida_gum/windows-x86_64\frida-gum.h(18379): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
> 3rd/frida_gum/gumpp/src/internal/override_gumdbghelp.c(160): warning C4996: 'wcscpy': This function or variable may be unsafe. Consider using wcscpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
> 3rd/frida_gum/gumpp/src/invocationlistener.cpp(165): warning C5051: 特性“noinline”至少需要“/std:c++20”；已忽略
> src\launcher\hook\vmhook_template.hpp(24): warning C4390: “;”: 找到空的受控语句；这是否是有意的?
> LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
> ```
> 
> 解决不了的警告，就禁用它

我去为什么咱们看到的结果不一样. 你什么vc版本,vc143的?

2023-02-28 13:37 UTC, actboy168 commented on src/launcher/autoattach.cpp
> +    }
这个是什么

2023-02-28 13:38 UTC, actboy168 commented
> 我去为什么咱们看到的结果不一样. 你什么vc版本,vc143的?

msvc 17.5.0

2023-03-01 01:41 UTC, fesily commented
> > 我去为什么咱们看到的结果不一样. 你什么vc版本,vc143的?
> 
> msvc 17.5.0

OK了

2023-03-01 01:42 UTC, fesily commented on src/launcher/autoattach.cpp
> +    }
扫描签名的部分,这个部分可能还要重新写一下

2023-03-01 01:45 UTC, fesily commented
我发现一个问题,在attach模式下launcher在已有进程内是得不到很多配置的.因为现在很多配置你可以看到直接用的getenv环境变量来传递的.
我的想法是lua-debug在文件中把配置信息填好,launcher直接去读文件,就类型与现在的IPC功能,在这个基础上进行扩展.
不过我感觉不需要这个PR里实行

2023-03-01 02:09 UTC, actboy168 commented
有什么配置？

2023-03-01 02:12 UTC, fesily commented on src/launcher/symbol_resolver/gum_resolver.cpp
> +            auto key = keys.back().data();
我设想的是这个key是形式上类似lua51.lua_settop可以被特定版本的所覆盖的,你可以看到unkown.cpp中key到名字都是这种形式,这也是为了特征吗扫描做的功能.每个lua版本的同名api特征吗八成不会相同

2023-03-01 02:19 UTC, fesily commented
> 有什么配置？

已有的设定配置:
1. LUA_DEBUG_VERSION:指定lua的版本值为:`jit` `5.1` `5.2` `5.3` `5.4` `latest`
2. LUA_DEBUG_HOOK_ENTRY:指定hook哪些函数以用来覆盖unknow中的默认的设置,值形式为`[lua版本.][函数名];[lua版本.][函数名];...`
举个例子:
`lua51.lua_settop;lua_pcall;luajit.lua_call`
这种情况下将根据luaversion来决定使用哪些hook的函数名
3. LUA_DEBUG_SIGNATURE: 指定函数特征吗,格式`[lua版本.][函数名]=“?? 99 ff”;[lua版本.][函数名]=“?? 99 ff”;....`

2023-03-01 02:20 UTC, actboy168 commented on src/launcher/symbol_resolver/gum_resolver.cpp
> +            auto key = keys.back().data();
既然不是这个版本的代码就先去掉吧。

2023-03-01 02:21 UTC, actboy168 commented on src/launcher/autoattach.cpp
> +    }
不是这个版本的代码就先去掉吧。

2023-03-01 02:23 UTC, actboy168 commented
> > 有什么配置？
> 
> 已有的设定配置:
> 
> 1. LUA_DEBUG_VERSION:指定lua的版本值为:`jit` `5.1` `5.2` `5.3` `5.4` `latest`
> 2. LUA_DEBUG_HOOK_ENTRY:指定hook哪些函数以用来覆盖unknow中的默认的设置,值形式为`[lua版本.][函数名];[lua版本.][函数名];...`
>    举个例子:
>    `lua51.lua_settop;lua_pcall;luajit.lua_call`
>    这种情况下将根据luaversion来决定使用哪些hook的函数名
> 3. LUA_DEBUG_SIGNATURE: 指定函数特征吗,格式`[lua版本.][函数名]=“?? 99 ff”;[lua版本.][函数名]=“?? 99 ff”;....`
> 
> 现在第三个未使用

这个可以之后再做。就这个PR来说，我觉得可以先去掉。

2023-03-01 02:25 UTC, fesily commented
> 


LUA_DEBUG_SIGNATURE代码已经删掉了

2023-03-01 05:15 UTC, actboy168 commented
> > 
> 
> LUA_DEBUG_SIGNATURE代码已经删掉了

其他的getenv也先删了吧

2023-03-01 06:51 UTC, fesily commented
我确定是launcher模式的问题, 我复现了你之前的错误. 连LLDB都无法附加到这个进程里. 这个console模式是内嵌在vscode进程里的吗?

2023-03-01 07:16 UTC, actboy168 commented
console模式是用了bee的api来启动进程。

你可以先试试用launch模式启动一个进程，能不能attach到这个进程？

现在的流程是先spawn一个暂停状态的进程，调用inject，然后让进程恢复运行。这个步骤对windows来说是没问题的，但可能macos是无法inject一个完全没用运行过的进程？

2023-03-01 07:19 UTC, fesily commented
首先之前的task_for_pid错误是因为lua进程已经执行完毕了,按照你之前的逻辑,是需要暂停方式启动来保证inject时候进程一定还存活

2023-03-01 08:55 UTC, fesily commented
确定是因为POSIX_SPAWN_START_SUSPENDED标志导致的
POSIX_SPAWN_START_SUSPENDED在macos上是停止在dyld::start函数之前,这个时候什么依赖库都没有加载.
时机完全不对,使用不了任何功能

2023-03-01 08:59 UTC, fesily commented
两个平台两种模式可以用了

2023-03-01 09:03 UTC, actboy168 commented
如果不能在inject前把进程停住的话，就可能会出现无法将调试器暂停在第一行。

2023-03-01 09:10 UTC, fesily commented
> 

那麻烦了,需要加入ptrace,加入中断替换指令,还得手工找main函数入口,

粗暴一点的方式就是直接在启动进程之后在启动一个lldb来在进程的main函数的时候加载进去

2023-03-01 09:47 UTC, actboy168 commented
听起来用ptrace比较好一点，这个可以下一步再做。

2023-03-01 10:02 UTC, actboy168 commented
我的macos上没用wget，但是curl似乎是默认自带的。所以用curl比较好？

2023-03-01 10:56 UTC, fesily commented
两者没差别，我记得wget是在linux默认的，curl在powershell不太对

2023-03-01 10:57 UTC, actboy168 commented
每个平台可以用不同的

2023-03-02 02:20 UTC, fesily commented
macos下launcher模式现在强制用lldb执行.我刚才仔细检查了一下出错的地方, 准确说那个时间点不能执行线程注入.除非使用DYLD_INSERT_LIBRARIES,但是这个功能不一定在任何进程内有效,进程可以自己屏蔽掉这个功能

2023-03-02 06:00 UTC, fesily commented
现在的代码就算告一段落了.
下一步路线:
1. 修复windows的注入器
2. 加入特征吗扫描
3. 在构建时生成默认的特征库

2023-03-02 09:43 UTC, actboy168 requested changes

2023-03-02 09:43 UTC, actboy168 commented on src/launcher/autoattach.cpp
> +                    memcpy_s(rm.path, sizeof(rm.path), path.c_str(), path.size());
这两行看起来没用任何作用

2023-03-02 09:54 UTC, actboy168 commented
为什么windows和macos查找lua模块的代码是不同的？

2023-03-02 10:00 UTC, actboy168 requested changes

2023-03-02 10:00 UTC, actboy168 commented on src/launcher/autoattach.cpp
> +		auto p = Gum::Process::module_find_symbol_by_name(path, "lua_ident");;
从函数定义看，这里是module_name,但传的却是path？

2023-03-02 10:21 UTC, fesily commented
> 为什么windows和macos查找lua模块的代码是不同的？

可以一样，删掉Windows部分，

2023-03-02 10:48 UTC, fesily commented
> > 为什么windows和macos查找lua模块的代码是不同的？
> 
> 可以一样，删掉Windows部分，

Windows可以一次调用匹配函数，其他平台的都不行

2023-03-02 12:28 UTC, actboy168 requested changes

2023-03-02 12:28 UTC, actboy168 commented on src/launcher/lua_resolver.cpp
> +        }
这个代码对于find这个函数是没用的，如果需要切割，应该是调用find的地方负责把它切割好。

2023-03-02 15:18 UTC, actboy168 requested changes

2023-03-02 15:18 UTC, actboy168 commented on src/launcher/autoattach.cpp
> +            return lua_version::luajit;
这个·函数没有用到path，所以有可能会找到另一个模块里的函数？

2023-03-03 00:57 UTC, fesily commented
关于进程中存在多个lua模块的问题,应该需要正确处理
的确有可能会出现多个lua模块在进程中. 

---

有以下的解决方法:

1. 每个模块都加载调试器
2. 由用户配置项来指定lua版本号
3. 使用查找到的第一个模块

2023-03-03 01:03 UTC, actboy168 commented
> 关于进程中存在多个lua模块的问题,应该需要正确处理 的确有可能会出现多个lua模块在进程中.
> 
> 有以下的解决方法:
> 
> 1. 每个模块都加载调试器
> 2. 由用户配置项来指定lua版本号
> 3. 使用查找到的第一个模块

嗯，我觉得暂时可以先用方案3就行了。

2023-03-03 01:51 UTC, fesily commented
> 

下一步吧

2023-03-03 02:01 UTC, actboy168 requested changes

2023-03-03 02:01 UTC, actboy168 commented on src/launcher/autoattach/autoattach.cpp
> +    void wait_lua_module() {
调用wait_lua_module的地方被删了

2023-03-03 03:51 UTC, actboy168 commented
现在调试器加载的时候（call attach.lua)，可能luaL_openlibs还没调用，所以前几次attach.lua会失败，直到某一次luaL_openlibs调用后才会成功。

可能的解决办法：
1. 确保luaL_openlibs之后，再call attach.lua。
2. 增加一个测试lua，检测需要的函数都已经存在，再call attach.lua。
3. 调试器加载代码不依赖任何标准库函数。debugger内的大多数代码是在检测lua version、arch、os等，这些launcher都另一套逻辑在做，做两次没必要也可能导致两次计算不一致。然后可能需要写几个c函数（例如load remotedebug.dll）供attach.lua使用。

2023-03-03 04:19 UTC, fesily commented
> 现在调试器加载的时候（call attach.lua)，可能luaL_openlibs还没调用，所以前几次attach.lua会失败，直到某一次luaL_openlibs调用后才会成功。
> 
> 可能的解决办法：
> 
> 1. 确保luaL_openlibs之后，再call attach.lua。
> 2. 增加一个测试lua，检测需要的函数都已经存在，再call attach.lua。
> 3. 调试器加载代码不依赖任何标准库函数。debugger内的大多数代码是在检测lua version、arch、os等，这些launcher都另一套逻辑在做，做两次没必要也可能导致两次计算不一致。然后可能需要写几个c函数（例如load remotedebug.dll）供attach.lua使用。



> 现在调试器加载的时候（call attach.lua)，可能luaL_openlibs还没调用，所以前几次attach.lua会失败，直到某一次luaL_openlibs调用后才会成功。
> 
> 可能的解决办法：
> 
> 1. 确保luaL_openlibs之后，再call attach.lua。
> 2. 增加一个测试lua，检测需要的函数都已经存在，再call attach.lua。
> 3. 调试器加载代码不依赖任何标准库函数。debugger内的大多数代码是在检测lua version、arch、os等，这些launcher都另一套逻辑在做，做两次没必要也可能导致两次计算不一致。然后可能需要写几个c函数（例如load remotedebug.dll）供attach.lua使用。

首先luaL_openlibs不一定被调用,人家的使用方式可以只使用特定的几个库,所以不能依赖这个行为的成立.
最保险的做法就是我们自己调用luaL_openlibs.因为调试器所需要的API即使独立出去做一套,后面宿主环境不加载luaL_openlibs照样起不来.
不过我觉得这种非常非常特殊的情况还是暂时不用理会了.可以以后做个配置来处理

综上,现在最合理的方式就是第二条,添加一个测试lua

2023-03-03 04:31 UTC, fesily commented
我先改了一步,允许debuggerAttach失败

2023-03-03 04:33 UTC, fesily commented
我觉得attach.lua应该有一个返回值,如果失败的话,来指示外部需不需要继续等待,之前的逻辑是调用了attach就解除了所有hook

2023-03-03 04:58 UTC, actboy168 commented
自己调用luaL_openlibs会影响调试目标的行为，比如它并不想加载所有的标准库函数。remotedebug除了eval，其他应该都是不依赖luaL_openlibs的。eval的问题可以以后遇到问题再解决。

2023-03-03 05:04 UTC, fesily commented
> 自己调用luaL_openlibs会影响调试目标的行为，比如它并不想加载所有的标准库函数。remotedebug除了eval，其他应该都是不依赖luaL_openlibs的。eval的问题可以以后遇到问题再解决。

如果是基于这种考虑,也就放弃这种连base库都不打开的环境了

2023-03-03 05:12 UTC, actboy168 commented
这种情况还挺常见的，至少我用的几个项目都不同程度地修改了luaL_openlibs。最常见的就是禁用io或者io指向非本地文件。

2023-03-03 05:17 UTC, fesily commented
> 

嗯,应该是只用了一部分的居多,完全不调用base库的应该不管他.

2023-03-03 05:20 UTC, actboy168 requested changes

2023-03-03 05:20 UTC, actboy168 commented on extension/script/attach.lua
> +end
这个为什么要改？

2023-03-03 05:27 UTC, fesily commented
> 现在调试器加载的时候（call attach.lua)，可能luaL_openlibs还没调用，所以前几次attach.lua会失败，直到某一次luaL_openlibs调用后才会成功。
> 
> 可能的解决办法：
> 
> 1. 确保luaL_openlibs之后，再call attach.lua。
> 2. 增加一个测试lua，检测需要的函数都已经存在，再call attach.lua。
> 3. 调试器加载代码不依赖任何标准库函数。debugger内的大多数代码是在检测lua version、arch、os等，这些launcher都另一套逻辑在做，做两次没必要也可能导致两次计算不一致。然后可能需要写几个c函数（例如load remotedebug.dll）供attach.lua使用。

我现在想想最准确的做法是launch模式应该hook lua_newstate,直接在这个地方挂上lua_hook,这样也就不用管其他地方的hook,但是还是要判断基础库初始化完成了没有

2023-03-03 08:01 UTC, actboy168 commented
简单的解决这个问题，方案2就行了。不过我觉得方案3是一个更好的方案，只是更复杂。

2023-03-03 08:28 UTC, fesily commented
> 简单的解决这个问题，方案2就行了。不过我觉得方案3是一个更好的方案，只是更复杂。

嗯,后面在加进去好了,顺带的事情

2023-03-03 14:08 UTC, actboy168 requested changes

2023-03-03 14:08 UTC, actboy168 commented on src/launcher/hook/luajit_listener.cpp
> +}
这几个函数似乎什么都没做

2023-03-05 05:00 UTC, actboy168 commented
现在debugger.lua里判断luajit的方法是是否有全局变量jit。但是因为现在可能在luaL_openlibs之前，就开始加载，所以jit变量可能还没初始化，这个时候加载调试器就会被识别为lua5.1。

2023-03-05 05:55 UTC, fesily commented
> 

两个方案 一，跟之前一样hook luaL_openlobs
二，在外面就加载好remotedebug，因为下一步这个工作也是要做的

2023-03-05 06:07 UTC, actboy168 commented
基本思路还是先怎么简单怎么做。先按旧方法做，下一步再做改进。

2023-03-05 06:17 UTC, actboy168 commented
现在launch并没有保证一定能识别到lua的版本号，当识别为unknown时，是无法加载remotedebug的。

所以首先要改进launch的版本识别。几个可能的改进点：
1. 用户配置lua版本，现在launch.json可以配置lua版本，但目前没有传递给launcher。
2. 增加类似debugger.lua中的版本识别机制，这个需要读取全局变量，所以得在得到L之后，再识别一次？
3. 所有的识别机制都识别不到，用户也没有配置，就让laucnher失败。

2023-03-05 06:17 UTC, actboy168 commented
现在launch并没有保证一定能识别到lua的版本号，当识别为unknown时，是无法加载remotedebug的。

所以首先要改进launch的版本识别。几个可能的改进点：
1. 用户配置lua版本，现在launch.json可以配置lua版本，但目前没有传递给launcher。
2. 增加类似debugger.lua中的版本识别机制，这个需要读取全局变量，所以得在得到L之后，再识别一次？
3. 所有的识别机制都识别不到，用户也没有配置，就让laucnher失败。

2023-03-05 06:54 UTC, fesily commented
launch得到unknown不代表 lua层也得不到。这两两个机制应该是独立开。用户配置＞launch得到的版本＞attach.lua的版本，他们应该是一种覆盖关系，所以我觉得launch应该直接传入自己得到的版本号，除非是unknown.

2023-03-05 07:20 UTC, actboy168 commented
现在的问题就是当launcher识别为unknown，lua层的luaL_openlibs不完全加载导致识别不出luajit，两者叠加，还是会让remotedebug加载错误的版本。所以得让这种情况下让launcher直接失败。

不过现在lua层的版本检测的问题是，无法区分这是一个luaL_openlibs不完全加载的luajit，还是一个lua51.

2023-03-05 13:29 UTC, fesily commented
> 现在的问题就是当launcher识别为unknown，lua层的luaL_openlibs不完全加载导致识别不出luajit，两者叠加，还是会让remotedebug加载错误的版本。所以得让这种情况下让launcher直接失败。
> 
> 不过现在lua层的版本检测的问题是，无法区分这是一个luaL_openlibs不完全加载的luajit，还是一个lua51.

按照之前的说法,hook luaL_openlibs之后将不会出现加载一般进入attach.lua, 所以这个问题应该不存在

2023-03-05 13:30 UTC, actboy168 commented
嗯，我是说要用新的hook方法，需要解决的问题。

2023-03-06 01:03 UTC, fesily commented
> 嗯，我是说要用新的hook方法，需要解决的问题。

我思考了一下,可以不依赖jit对象来确定是否为luajit版本.依赖luajit在标准库上的不一致结果就行了

2023-03-06 01:08 UTC, fesily commented
> > 嗯，我是说要用新的hook方法，需要解决的问题。
> 
> 我思考了一下,可以不依赖jit对象来确定是否为luajit版本.依赖luajit在标准库上的不一致结果就行了

这样也不用hook luaL_openlibs了

2023-03-06 01:18 UTC, actboy168 requested changes

2023-03-06 01:18 UTC, actboy168 commented on extension/script/debugger.lua
>              jit.off()
jit可能为nil

2023-03-06 01:19 UTC, actboy168 requested changes

2023-03-06 01:19 UTC, actboy168 commented on extension/script/attach.lua
> +    return "wait initialized"
应该在这里检测luajit，然后等待jit变量初始化？

2023-03-06 07:05 UTC, actboy168 commented on src/launcher/hook/watchdog.cpp
> +        }
inwatch确保了watch_entry只会执行一次，所以在这里就可以调用unhook了？因为后续watch_entry再被调用也没有任何意义了。

2023-03-08 06:30 UTC, actboy168 commented
windows 看起来已经没问题了。不够现在macos我编译会出这个警告，然后还是无法启动调试。
```
ld: warning: ignoring file 3rd/frida_gum/macos-x86_64/libfrida-gum.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x23 0x31 0x2F 0x32 0x30 0x20 0x20 0x20 )
```

2023-03-08 09:09 UTC, fesily commented
> windows 看起来已经没问题了。不过现在macos我编译会出这个警告，然后还是无法启动调试。
> 
> ```
> ld: warning: ignoring file 3rd/frida_gum/macos-x86_64/libfrida-gum.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x23 0x31 0x2F 0x32 0x30 0x20 0x20 0x20 )
> ```

clang是什么版本,我没有这个问题
```shell
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

2023-03-08 09:30 UTC, actboy168 commented
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

2023-03-08 09:32 UTC, actboy168 commented
> ```
> Apple clang version 14.0.0 (clang-1400.0.29.202)
> Target: arm64-apple-darwin22.1.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> ```

我重新下一个frida看看

2023-03-08 09:55 UTC, actboy168 commented
重新下载可以解决警告，但还是启动不了。

2023-03-08 10:03 UTC, fesily commented
什么配置

2023-03-09 09:48 UTC, actboy168 commented
```json

        {
            "type": "lua",
            "request": "launch",
            "name": "Test",
            "luaVersion": "latest",
            "stopOnEntry": true,
            "inject": "lldb",
            "runtimeExecutable": "${command:extensionPath}actboy168.lua-debug-1.61.0-darwin-arm64/runtime/darwin-arm64/lua54/lua",
            "runtimeArgs": "test.lua",
        },
```

2023-03-09 09:50 UTC, actboy168 requested changes

2023-03-09 09:53 UTC, actboy168 commented
我觉得现在的问题是，启动进程，然后再注入，再下断点。在断点下好之前进程可能就已经结束了。

2023-03-09 10:01 UTC, actboy168 requested changes

2023-03-09 10:01 UTC, actboy168 commented on extension/script/frontend/debuger_factory.lua
> +            end
这个有点画蛇添足，真正的错误信息会更有用

2023-03-10 00:47 UTC, fesily commented
> ```json
>        {
>             "type": "lua",
>             "request": "launch",
>             "name": "Test",
>             "luaVersion": "latest",
>             "stopOnEntry": true,
>             "inject": "lldb",
>             "runtimeExecutable": "${command:extensionPath}actboy168.lua-debug-1.61.0-darwin-arm64/runtime/darwin-arm64/lua54/lua",
>             "runtimeArgs": "test.lua",
>         },
> ```

按照之前的逻辑你使用inject.lldb是无法进入的,使用hook是可以启动的.
现在我改了一下,可以使用lldb进入了

2023-03-10 04:49 UTC, actboy168 commented
嗯现在可以了

2023-03-10 04:56 UTC, actboy168 requested changes

2023-03-10 04:56 UTC, actboy168 commented on compile/common/package_json.lua
> +end
现在只支持windows和macos？

2023-03-10 04:56 UTC, actboy168 commented on compile/common/package_json.lua
> +
同上

2023-03-10 05:28 UTC, fesily commented
lldb模式是支持在Linux进行注入的,但是相关代码都没写,所以我先把linux的入口都关掉

2023-03-10 05:36 UTC, actboy168 commented
现在macos支持两种注入方式，但是其中一种要满足很多前置条件才能使用。我觉得不应该在失败是退到其他注入方式，而是给出错误提示，让用户自己切换。

此外lldb的注入方式，应该可以加个简单的检测，如果用户没有lldb，能给个更友好的错误提示。

2023-03-10 05:37 UTC, actboy168 requested changes

2023-03-10 05:37 UTC, actboy168 commented on compile/common/package_json.lua
> +
应该只有macos才支持lldb

2023-03-10 05:37 UTC, actboy168 commented on compile/common/package_json.lua
> +
同上

2023-03-10 05:53 UTC, fesily commented
> 现在macos支持两种注入方式，但是其中一种要满足很多前置条件才能使用。我觉得不应该在失败是退到其他注入方式，而是给出错误提示，让用户自己切换。
> 
> 此外lldb的注入方式，应该可以加个简单的检测，如果用户没有lldb，能给个更友好的错误提示。

现在并不会自动🔙其他方案

现在没有lldb的提示是
```
Spwan lldb failed:subprocess::spawn: No such file or directory
```

2023-03-10 05:59 UTC, fesily commented
> > 现在macos支持两种注入方式，但是其中一种要满足很多前置条件才能使用。我觉得不应该在失败是退到其他注入方式，而是给出错误提示，让用户自己切换。
> > 此外lldb的注入方式，应该可以加个简单的检测，如果用户没有lldb，能给个更友好的错误提示。
> 
> 现在并不会自动🔙其他方案
> 
> 现在没有lldb的提示是
> 
> ```
> Spwan lldb failed:subprocess::spawn: No such file or directory
> ```

我改善一下出错的提示,macos详细区分提示`inject.hook`模式下的错误来源

2023-03-10 06:04 UTC, actboy168 commented
> > > 现在macos支持两种注入方式，但是其中一种要满足很多前置条件才能使用。我觉得不应该在失败是退到其他注入方式，而是给出错误提示，让用户自己切换。
> > > 此外lldb的注入方式，应该可以加个简单的检测，如果用户没有lldb，能给个更友好的错误提示。
> > 
> > 
> > 现在并不会自动🔙其他方案
> > 现在没有lldb的提示是
> > ```
> > Spwan lldb failed:subprocess::spawn: No such file or directory
> > ```
> 
> 我改善一下出错的提示,macos详细区分提示`inject.hook`模式下的错误来源

我的意思是不符合inject==hook的条件时，就失败，而不是改到lldb

2023-03-10 06:13 UTC, fesily commented
> 

👌,删掉了,现在提示让用户手动切换

2023-03-10 09:48 UTC, merged