fix luancher crash
actboy168/lua-debug pull request #245
Opened 2023-03-25 05:29 UTC by fesily

waitdll的时候,出现以下情形:
上一次attach的处理流程还在waitdll.
又主动attach进来,导致两个线程在跑start函数.

当前launcher不是纯粹的无状态的代码,有竞态条件的

2023-03-25 07:54 UTC, fesily commented
这个问题应该有更好的方案
比如说加入一个全局环境变量context,每次attach都是新建一个context,除了这个变量不使用任何其他全局变量.

2023-03-25 09:50 UTC, actboy168 commented
首先先把问题拆分成两个
1. 对同一个lua模块，多次调用launcher
2. 对不同的lua模块，多次调用launcher

对于问题2，目前的代码应该还差很多，暂时可以不考虑。
对于问题1，首先launcher需要有地方确保多次调用launcher是针对同一个lua模块。然后我觉得start应该是要允许多次调用，我们应该把现在还不能并发的地方改掉。

最后waitdll也确实可以限制它全局唯一实例，因为同时调用多个waitdll似乎也没什么意义。

2023-03-27 02:29 UTC, fesily commented
> 首先先把问题拆分成两个
> 
> 1. 对同一个lua模块，多次调用launcher
> 2. 对不同的lua模块，多次调用launcher
> 
> 对于问题2，目前的代码应该还差很多，暂时可以不考虑。 对于问题1，首先launcher需要有地方确保多次调用launcher是针对同一个lua模块。然后我觉得start应该是要允许多次调用，我们应该把现在还不能并发的地方改掉。
> 
> 最后waitdll也确实可以限制它全局唯一实例，因为同时调用多个waitdll似乎也没什么意义。

start并发需要,有一个固定的`gum::interceptor`,不然会重复hook
想要保证同一个module_path,那就得存一下,之前的结果.
那其实应该加一个全局变量

2023-03-29 06:02 UTC, fesily commented
👌,测试了一遍

2023-03-29 09:57 UTC, actboy168 commented
同一个lua模块的watchdog，应该是可以复用的。或者说，第二次attach，launcher应该什么都不需要做。

2023-03-30 02:53 UTC, fesily commented
> 同一个lua模块的watchdog，应该是可以复用的。或者说，第二次attach，launcher应该什么都不需要做。

hook还是要做的,其他的可以不做

2023-03-30 08:38 UTC, actboy168 commented
worker应该也没有退

2023-03-30 08:41 UTC, fesily commented
> worker应该也没有退

我测试看看

2023-03-31 05:30 UTC, fesily commented
> 

的确可以

2023-04-01 01:05 UTC, fesily commented
有空reveiw一下

但是对于luadebug不能彻底卸载的问题,我觉得需要提供一个方案来提供优雅退出,现在等于说管杀不管埋.

2023-04-01 01:24 UTC, actboy168 commented
我觉得没有必要，甚至DAP也没有结束调试器但不退出进程的协议。
如果自己驱动update事件的话，在调试器前端不存在时，调试器后端对调试目标就是零影响。

2023-04-01 01:37 UTC, actboy168 commented on src/launcher/autoattach/lua_module.h
> +        std::shared_ptr<struct watchdog> watchdog;
我觉得watchdog应该和luamodule一一绑定，所以不明白这样改的意义。

2023-04-01 02:03 UTC, fesily commented on src/launcher/autoattach/lua_module.h
> +        std::shared_ptr<struct watchdog> watchdog;
我的想法是需要管理watchdog的生命周期
shared_ptr 纯属在
```c++
watchdog = create_watchdog(attach_lua_vm, version, resolver);
```
这里不需要引用watchdog的头文件.

当然情形是没有做资源释放.

2023-04-01 02:05 UTC, fesily commented
> 我觉得没有必要，甚至DAP也没有结束调试器但不退出进程的协议。 如果自己驱动update事件的话，在调试器前端不存在时，调试器后端对调试目标就是零影响。

但我的想法一直都是需要释放掉产生资源的.
因为除了手机和电脑不在乎内存使用的大小,单片机上能用的内存很小的.以mb计算.

2023-04-01 02:08 UTC, fesily commented on src/launcher/autoattach/lua_module.h
> +        std::shared_ptr<struct watchdog> watchdog;
的确绑定在一起也比较方便.可以在lua_module的析构函数里做

2023-04-01 02:31 UTC, actboy168 commented
对于调试器而言，当你不需要它时，最直接的办法是不加载它，甚至不要带上调试器二进制和代码。

2023-04-01 02:34 UTC, actboy168 requested changes

2023-04-01 02:34 UTC, actboy168 commented on src/launcher/hook/watchdog.cpp
> +        : interceptor { ctx::get()->interceptor }
多个watchdog，只要它们不是针对同一个luamodule的，它们应该也是可以共存的

2023-04-01 02:46 UTC, actboy168 commented
与其考虑luadebug的退出，不如先解决launcher退出的问题。因为launcher有hook，它的退出更有意义。

现在launcher的退出时机，需要luadebug提供，所以launcher需要导出一个函数给luadebug, 这个函数可以将launcher的一个luamodule退出，当所有的luamodule都已经退出后，launcher可以将自己退出。

2023-04-01 03:00 UTC, fesily commented
> 与其考虑luadebug的退出，不如先解决launcher退出的问题。因为launcher有hook，它的退出更有意义。
> 
> 现在launcher的退出时机，需要luadebug提供，所以launcher需要导出一个函数给luadebug, 这个函数可以将launcher的一个luamodule退出，当所有的luamodule都已经退出后，launcher可以将自己退出。

这个功能我已经考虑过了,等现有的功能先合并完了,在做一个

2023-04-01 04:58 UTC, actboy168 commented on src/launcher/autoattach/ctx.h
> +        fn_attach debuggerAttach;
其实这个函数只是一个全局的静态函数，不需要记下来，要用的地方直接用好了。

2023-04-01 04:58 UTC, actboy168 commented on src/launcher/hook/watchdog.h
> +        std::atomic_bool inwatch = true;  // unlock when hooked
这个的作用是？

2023-04-01 05:01 UTC, fesily commented on src/launcher/hook/watchdog.h
> +        std::atomic_bool inwatch = true;  // unlock when hooked
会出现这种情况,hook完第一个函数,就触发回调了
先用true屏蔽回调函数,保证不会出现多线程执行的情况

2023-04-01 05:23 UTC, actboy168 commented on src/launcher/hook/watchdog.h
> +        std::atomic_bool inwatch = true;  // unlock when hooked
首先，两个功能共用了一个flags，我觉得不是很好，inwatch也不能很好地表达这个意思。
其次，第一个被触发的hook被跳过了，最好第一个触发的hook就把流程进行下去。
或许在在这两个函数里加一个互斥锁。

2023-04-01 05:41 UTC, fesily commented on src/launcher/hook/watchdog.h
> +        std::atomic_bool inwatch = true;  // unlock when hooked
那就改成mutex,比较清晰一点

2023-04-04 07:22 UTC, actboy168 requested changes

2023-04-04 07:22 UTC, actboy168 commented on src/launcher/autoattach/autoattach.cpp
> +        }
这个看起来并不能避免wait_dll的重复调用。如果第一次start调用了wait_dll，第二次start时，第一次的wait_dll还没结束，这时又会调用wait_dll。

2023-04-04 07:22 UTC, actboy168 commented on src/launcher/hook/watchdog.cpp
> +            return;
这里不应该用try_lock,而是用lock。

2023-04-04 07:22 UTC, actboy168 commented on src/launcher/hook/watchdog.cpp
> +        set_luahook(L, fn);
仔细考虑了这里的代码，不能说有错，但是和重写之前的代码逻辑是不一样的。现在的代码只会在第一个遇到的lua vm里加载调试器，而之前的会在所有的vm里加载调试器。

所以这里还需要把hook过的vm记住，如果没有hook过就调用set_luahook。

2023-04-04 09:02 UTC, fesily commented on src/launcher/autoattach/autoattach.cpp
> +        }
的确,会有这个问题,添加一个标记,不重复进入wait_dll的逻辑,但整个逻辑还是走一遍.

2023-04-04 09:24 UTC, actboy168 commented on src/launcher/hook/watchdog.cpp
> +        set_luahook(L, fn);
我是说，launcher在被你重写前是这个逻辑

2023-04-04 09:49 UTC, fesily commented on src/launcher/hook/watchdog.cpp
> +        set_luahook(L, fn);
的确是这样,那有个问题了,难道全程hook着? 对于单VM的没必要.

2023-04-04 09:58 UTC, fesily commented on src/launcher/hook/watchdog.cpp
> +        set_luahook(L, fn);
我的想法是
1. 添加一个永远有效的lua_newstate
2. launch模式下只用lua_newstate
3. attach模式下加一个mulit_vm的配置,启用的时候永远不unhook

2023-04-04 11:34 UTC, fesily commented on src/launcher/hook/watchdog.cpp
> +        set_luahook(L, fn);
🆗,我改好了,你在看看

2023-04-06 02:37 UTC, merged

2023-04-06 03:16 UTC, actboy168 commented
@fesily 还有些错误，lua_newstate的第一个参数不是L

2023-04-06 03:31 UTC, fesily commented
> @fesily 还有些错误，lua_newstate的第一个参数不是L

嗯,下午我改下